### ISSUE TITLE
Praat-Parselmouth for noise reduction?

### ISSUE THREAD

**Issue by qo4on** [drfeinberg/Parselmouth-Guides#1]
Thanks for your tutorials!
Do you know how I can remove noise from audio based on the sample of noise with Praat-Parselmouth?

**Comment by drfeinberg** [comment]
If you can find the part of sound with only the noise, but not the signal in it, you can specify that time range and use that. Praat/Parselmouth will subtract those frequencies from the signal.

**Comment by qo4on** [comment]
I can't find the part of sound with only the noise. The location of this part is different for each audio file. I prepared a file which contains only the noise. Is it possible to use it to subtract those frequencies from other files?

**Comment by drfeinberg** [comment]
I don't know.  I never used the function before.  If you can't, you can always concatenate the sounds (recoverably) and sample from there.

**Comment by qo4on** [comment]
Ok, thank you!
