### ISSUE TITLE
Audio equalizer

### ISSUE THREAD

**Issue by qo4on** [drfeinberg/Parselmouth-Guides#2]
Do you have any guide for EQ? Something like 30 band equalizer?
I found that it is [possible to do](http://www.praatvocaltoolkit.com/eq-10-bands.html), but I don't know the right command for Parselmouth.

**Comment by drfeinberg** [comment]
I've made something over the weekend for you.  It does the exact same thing as the script you posted but in parselmouth.  Bonus, if you run it in jupyter notebooks, you can use sliders for the equalizer.

**Comment by qo4on** [comment]
OH Thank You!
