### ISSUE TITLE
Change gender quality

### ISSUE THREAD

**Issue by qo4on** [drfeinberg/Parselmouth-Guides#3]
Hello sir!
I changed a pitch +1 and a formant +100 cents in Melodyne and got [much better results](https://www.dropbox.com/sh/bi6s8zcb0wyynk0/AACR2W_1EjuZCq5BnqvREfeWa) compare to Parselmouth. There are some artifacts when using Parselmouth but Melodyne sounds great. I used this code:
```
from scipy.io.wavfile import write

factor = 1.059463
sound = parselmouth.Sound("03-01-01-01-01-01-01.wav")
pitch = sound.to_pitch()
medain_pitch = call(pitch, "Get quantile", 0, 0, 0.5, "Hertz")
pitch_shift = medain_pitch + 17
manipulated_sound = call(sound, "Change gender", 100,
                         500, factor, pitch_shift, 1, 1)
write("03-01-01-01-01-01-01 parselmouth.wav", int(manipulated_sound.sampling_frequency), manipulated_sound.values.T.astype('float32'))
Audio(data=manipulated_sound.values, rate=manipulated_sound.sampling_frequency)
```
Do you know why this is happening and how to get better quality with Parselmouth?

**Comment by drfeinberg** [comment]
I am not an author of Praat.  You should ask them as they wrote the source code.
